package main

const (
	REDIS_CMD_BULK              = 1
	REDIS_CMD_INLINE            = 2
	REDIS_CMD_DENYOOM           = 4
	REDIS_CMD_FORCE_REPLICATION = 8
)

var cmds = map[string]int{
	"get":              REDIS_CMD_INLINE,
	"set":              REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"setnx":            REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"setex":            REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"append":           REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"substr":           REDIS_CMD_INLINE,
	"del":              REDIS_CMD_INLINE,
	"exists":           REDIS_CMD_INLINE,
	"incr":             REDIS_CMD_INLINE | REDIS_CMD_DENYOOM,
	"decr":             REDIS_CMD_INLINE | REDIS_CMD_DENYOOM,
	"mget":             REDIS_CMD_INLINE,
	"rpush":            REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"lpush":            REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"rpushx":           REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"lpushx":           REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"linsert":          REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"rpop":             REDIS_CMD_INLINE,
	"lpop":             REDIS_CMD_INLINE,
	"brpop":            REDIS_CMD_INLINE,
	"blpop":            REDIS_CMD_INLINE,
	"llen":             REDIS_CMD_INLINE,
	"lindex":           REDIS_CMD_INLINE,
	"lset":             REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"lrange":           REDIS_CMD_INLINE,
	"ltrim":            REDIS_CMD_INLINE,
	"lrem":             REDIS_CMD_BULK,
	"rpoplpush":        REDIS_CMD_INLINE | REDIS_CMD_DENYOOM,
	"sadd":             REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"srem":             REDIS_CMD_BULK,
	"smove":            REDIS_CMD_BULK,
	"sismember":        REDIS_CMD_BULK,
	"scard":            REDIS_CMD_INLINE,
	"spop":             REDIS_CMD_INLINE,
	"srandmember":      REDIS_CMD_INLINE,
	"sinter":           REDIS_CMD_INLINE | REDIS_CMD_DENYOOM,
	"sinterstore":      REDIS_CMD_INLINE | REDIS_CMD_DENYOOM,
	"sunion":           REDIS_CMD_INLINE | REDIS_CMD_DENYOOM,
	"sunionstore":      REDIS_CMD_INLINE | REDIS_CMD_DENYOOM,
	"sdiff":            REDIS_CMD_INLINE | REDIS_CMD_DENYOOM,
	"sdiffstore":       REDIS_CMD_INLINE | REDIS_CMD_DENYOOM,
	"smembers":         REDIS_CMD_INLINE,
	"eadd":             REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"eexpire":          REDIS_CMD_INLINE,
	"etotalcount":      REDIS_CMD_INLINE,
	"ecard":            REDIS_CMD_INLINE,
	"etopk":            REDIS_CMD_INLINE,
	"zadd":             REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"zincrby":          REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"zrem":             REDIS_CMD_BULK,
	"zremrangebyscore": REDIS_CMD_INLINE,
	"zremrangebyrank":  REDIS_CMD_INLINE,
	"zunionstore":      REDIS_CMD_INLINE | REDIS_CMD_DENYOOM,
	"zinterstore":      REDIS_CMD_INLINE | REDIS_CMD_DENYOOM,
	"zrange":           REDIS_CMD_INLINE,
	"zrangebyscore":    REDIS_CMD_INLINE,
	"zcount":           REDIS_CMD_INLINE,
	"zrevrange":        REDIS_CMD_INLINE,
	"zcard":            REDIS_CMD_INLINE,
	"zscore":           REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"zrank":            REDIS_CMD_BULK,
	"zrevrank":         REDIS_CMD_BULK,
	"hset":             REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"hsetnx":           REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"hget":             REDIS_CMD_BULK,
	"hmset":            REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"hmget":            REDIS_CMD_BULK,
	"hincrby":          REDIS_CMD_INLINE | REDIS_CMD_DENYOOM,
	"hdel":             REDIS_CMD_BULK,
	"hlen":             REDIS_CMD_INLINE,
	"hkeys":            REDIS_CMD_INLINE,
	"hvals":            REDIS_CMD_INLINE,
	"hgetall":          REDIS_CMD_INLINE,
	"hexists":          REDIS_CMD_BULK,
	"incrby":           REDIS_CMD_INLINE | REDIS_CMD_DENYOOM,
	"decrby":           REDIS_CMD_INLINE | REDIS_CMD_DENYOOM,
	"getset":           REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"mset":             REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"msetnx":           REDIS_CMD_BULK | REDIS_CMD_DENYOOM,
	"randomkey":        REDIS_CMD_INLINE,
	"select":           REDIS_CMD_INLINE,
	"move":             REDIS_CMD_INLINE,
	"rename":           REDIS_CMD_INLINE,
	"renamenx":         REDIS_CMD_INLINE,
	"expire":           REDIS_CMD_INLINE,
	"expireat":         REDIS_CMD_INLINE,
	"keys":             REDIS_CMD_INLINE,
	"dbsize":           REDIS_CMD_INLINE,
	"auth":             REDIS_CMD_INLINE,
	"ping":             REDIS_CMD_INLINE,
	"echo":             REDIS_CMD_BULK,
	"save":             REDIS_CMD_INLINE,
	"bgsave":           REDIS_CMD_INLINE,
	"bgrewriteaof":     REDIS_CMD_INLINE,
	"shutdown":         REDIS_CMD_INLINE,
	"lastsave":         REDIS_CMD_INLINE,
	"type":             REDIS_CMD_INLINE,
	"multi":            REDIS_CMD_INLINE,
	"exec":             REDIS_CMD_INLINE | REDIS_CMD_DENYOOM,
	"discard":          REDIS_CMD_INLINE,
	"sync":             REDIS_CMD_INLINE,
	"flushdb":          REDIS_CMD_INLINE,
	"flushall":         REDIS_CMD_INLINE,
	"sort":             REDIS_CMD_INLINE | REDIS_CMD_DENYOOM,
	"info":             REDIS_CMD_INLINE,
	"monitor":          REDIS_CMD_INLINE,
	"ttl":              REDIS_CMD_INLINE,
	"slaveof":          REDIS_CMD_INLINE,
	"debug":            REDIS_CMD_INLINE,
	"config":           REDIS_CMD_BULK,
	"subscribe":        REDIS_CMD_INLINE,
	"unsubscribe":      REDIS_CMD_INLINE,
	"psubscribe":       REDIS_CMD_INLINE,
	"punsubscribe":     REDIS_CMD_INLINE,
	"publish":          REDIS_CMD_BULK | REDIS_CMD_FORCE_REPLICATION,
	"watch":            REDIS_CMD_INLINE,
	"unwatch":          REDIS_CMD_INLINE,
}
